defaults:
  - algo: image_sac

exp_name: ???
checkpoint_freq: 1

gpu: 0 # assuming single GPU
seed: 0
server_port: 2000

data_module:
    batch_size: 32
    buffer_size: 1e5
    num_workers: 4
    dataset_paths: 
      # - '/home/brian/ml-multiple-futures-prediction/multiple_futures_prediction/carla_data/autopilot_5hz_data'
      # - '/home/scratch/brianyan/static_data_v2'
      # - '/home/scratch/brianyan/static_data_town02_v2'
      # - '/home/scratch/brianyan/static_data_town03_v2'
      # - '/home/scratch/brianyan/static_data_town04_v2'
      # - '/home/scratch/brianyan/static_data_town05_v2'
      # - '/home/brian/alta/agents/torch/sample_data'
      - '/home/scratch/brianyan/offline_data'
    train_val_split: 0.9
    use_images: false
    frame_stack: 1
    populate_size: 5000
    epoch_size: 20000
    train_every_n_steps: 20

environment:
    sample_npc: false
    scenarios: 'no_crash_empty'
    input_type: 'wp_obs_info_speed_steer_ldist_goal_light' # 'wp_bev_rv_obs_info_speed_steer_ldist_goal_light'
    sensors:
        sensor.camera.semantic_segmentation/top:
            name: 'sensor.camera.semantic_segmentation/top'
            x: 13.0
            z: 18.0
            pitch: 270.0
            sensor_x_res: '112'
            sensor_y_res: '112'
            fov: '90'
            sensor_tick: '0.0'
            num_classes: 5
        sensor.camera.rgb/front:
            name: 'sensor.camera.rgb/front'
            x: 2.0
            z: 1.4
            pitch: 0.0
            sensor_x_res: '112'
            sensor_y_res: '112'
            fov: '90'
            sensor_tick: '0.0'
        sensor.camera.semantic_segmentation/front:
            name: 'sensor.camera.semantic_segmentation/front'
            x: 2.0
            z: 1.4
            pitch: 0.0
            sensor_x_res: '112'
            sensor_y_res: '112'
            fov: '90'
            sensor_tick: '0.0'
            num_classes: 5
        lane_invasion_sensor:
        collision_sensor:
    # const_collision_penalty: 250
    # const_light_penalty: 250
    verbose: 0

eval_freq: 1
eval_length: 2000
num_eval_episodes: 1

train_offline: false
offline_epochs: 500

train_online: true
online_epochs: 10000


trainer:
    precision: 16
    gpus: ${gpu}

hydra:
    run:
        dir: /home/scratch/brianyan/outputs/${exp_name}/${now:%Y-%m-%d_%H-%M-%S}
