# # gpu 8
python ../run_code.py --algo SAC --task "self-driving" --scenarios "long_straight" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run1 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_long-straight/" --timesteps 8000000 --network 2_layer --lr 4e-4 --carla-gpu 0 --code-gpu 0 --steer-penalty-coeff 0 --const-collision-penalty 250 --collision-penalty-speed-coeff 250 --const-light-penalty 250 --light-penalty-speed-coeff 250 --buffer-size 1000000 --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef -1 --n-steps 1 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --scenarios "long_straight" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run2 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_long-straight/" --timesteps 8000000 --network 2_layer --lr 4e-4 --carla-gpu 0 --code-gpu 0 --steer-penalty-coeff 0 --const-collision-penalty 250 --collision-penalty-speed-coeff 250 --const-light-penalty 250 --light-penalty-speed-coeff 250 --buffer-size 1000000 --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef -1 --n-steps 1 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --scenarios "long_straight" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run3 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_long-straight/" --timesteps 8000000 --network 2_layer --lr 4e-4 --carla-gpu 3 --code-gpu 3 --steer-penalty-coeff 0 --const-collision-penalty 250 --collision-penalty-speed-coeff 250 --const-light-penalty 250 --light-penalty-speed-coeff 250 --buffer-size 1000000 --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef -1 --n-steps 1 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --scenarios "long_straight" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run4 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_long-straight/" --timesteps 8000000 --network 2_layer --lr 4e-4 --carla-gpu 3 --code-gpu 3 --steer-penalty-coeff 0 --const-collision-penalty 250 --collision-penalty-speed-coeff 250 --const-light-penalty 250 --light-penalty-speed-coeff 250 --buffer-size 1000000 --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef -1 --n-steps 1 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --scenarios "long_straight" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run5 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_long-straight/" --timesteps 8000000 --network 2_layer --lr 4e-4 --carla-gpu 3 --code-gpu 3 --steer-penalty-coeff 0 --const-collision-penalty 250 --collision-penalty-speed-coeff 250 --const-light-penalty 250 --light-penalty-speed-coeff 250 --buffer-size 1000000 --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef -1 --n-steps 1 &
sleep 60
