# # gpu 8
python ../run_code.py --algo SAC --task "self-driving" --run-id run1 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 1000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 1 --carla-gpu 1 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef 0.001 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --run-id run2 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 1000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 1 --carla-gpu 1 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef 0.001 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --run-id run3 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 1000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 1 --carla-gpu 1 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef 0.001 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --run-id run4 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 1000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 2 --carla-gpu 2 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef 0.001 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --run-id run5 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 1000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 2 --carla-gpu 2 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef 0.001 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --run-id run6 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 1000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 2 --carla-gpu 2 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef 0.001 &
sleep 60
