#! /bin/bash
#SBATCH -N 1
#SBATCH -p long
#SBATCH --gres gpu:2
#SBATCH --ntasks-per-node 32
#SBATCH -t 7-12:00:00

source ~/.bashrc

trap "kill $(jobs -p)" EXIT

#echo commands to stdout
set -x

#move to working directory
# this job assumes:
# - all input data is stored in this directory 
# - all output should be stored in this directory 
cd /home/tanmaya/projects/alta/agents/tf

#python run_code.py --algo PPO --input-type wp_vae --network CustomPolicy2 --base-log-dir '/home/tanmaya/alta-logs/new_env/ppo_runs/benchmark_navigation1/' --vae_model_path '/home/tanmaya/alta/agents/tf/trained_models/ae_model.json' --timesteps 1000000 --carla-gpu 0 --code-gpu 0 --finetune-vae --lr 2e-4 --run-id 4 &
#sleep 300
python run_code.py \
--algo PPO \
--input-type wp_obs_info_speed_steer_ldist_goal_light \
--network 2_layer \
--scenarios dynamic_navigation \
--timesteps 8000000 \
--num-npc 70 \
--const-collision-penalty 250 --collision-penalty-speed-coeff 250 \
--const-light-penalty 250 --light-penalty-speed-coeff 250 \
--base-log-dir '/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation/updated_monotonic/wp_obs_info_speed_steer_ldist_goal_light' \
--carla-gpu 0 --code-gpu 0 \
--n-steps 20000 \
--lr 2e-4 \
--no-epochs 10 \
--no-minibatches 10 \
--clip 0.2 \
--videos \
--run-id 1 &
sleep 60

python run_code.py \
--algo PPO \
--input-type wp_obs_info_speed_steer_ldist_goal_light \
--network 2_layer \
--scenarios dynamic_navigation \
--timesteps 8000000 \
--num-npc 70 \
--const-collision-penalty 250 --collision-penalty-speed-coeff 250 \
--const-light-penalty 250 --light-penalty-speed-coeff 250 \
--base-log-dir '/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation/updated_monotonic/wp_obs_info_speed_steer_ldist_goal_light' \
--carla-gpu 0 --code-gpu 0 \
--n-steps 20000 \
--lr 2e-4 \
--no-epochs 10 \
--no-minibatches 10 \
--clip 0.2 \
--videos \
--run-id 2 &
sleep 60

python run_code.py \
--algo PPO \
--input-type wp_obs_info_speed_steer_ldist_goal_light \
--network 2_layer \
--scenarios dynamic_navigation \
--timesteps 8000000 \
--num-npc 70 \
--const-collision-penalty 250 --collision-penalty-speed-coeff 250 \
--const-light-penalty 250 --light-penalty-speed-coeff 250 \
--base-log-dir '/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation/updated_monotonic/wp_obs_info_speed_steer_ldist_goal_light' \
--carla-gpu 0 --code-gpu 0 \
--n-steps 20000 \
--lr 2e-4 \
--no-epochs 10 \
--no-minibatches 10 \
--clip 0.2 \
--videos \
--run-id 3 &

python run_code.py \
--algo PPO \
--input-type wp_obs_info_speed_steer_ldist_goal_light \
--network 2_layer \
--scenarios dynamic_navigation \
--timesteps 8000000 \
--num-npc 70 \
--const-collision-penalty 250 --collision-penalty-speed-coeff 250 \
--const-light-penalty 250 --light-penalty-speed-coeff 250 \
--base-log-dir '/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation/updated_monotonic/wp_obs_info_speed_steer_ldist_goal_light' \
--carla-gpu 1 --code-gpu 1 \
--n-steps 20000 \
--lr 2e-4 \
--no-epochs 10 \
--no-minibatches 20 \
--clip 0.2 \
--videos \
--run-id 1 &
sleep 60

python run_code.py \
--algo PPO \
--input-type wp_obs_info_speed_steer_ldist_goal_light \
--network 2_layer \
--scenarios dynamic_navigation \
--timesteps 8000000 \
--num-npc 70 \
--const-collision-penalty 250 --collision-penalty-speed-coeff 250 \
--const-light-penalty 250 --light-penalty-speed-coeff 250 \
--base-log-dir '/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation/updated_monotonic/wp_obs_info_speed_steer_ldist_goal_light' \
--carla-gpu 1 --code-gpu 1 \
--n-steps 20000 \
--lr 2e-4 \
--no-epochs 10 \
--no-minibatches 20 \
--clip 0.2 \
--videos \
--run-id 2 &
sleep 60

python run_code.py \
--algo PPO \
--input-type wp_obs_info_speed_steer_ldist_goal_light \
--network 2_layer \
--scenarios dynamic_navigation \
--timesteps 8000000 \
--num-npc 70 \
--const-collision-penalty 250 --collision-penalty-speed-coeff 250 \
--const-light-penalty 250 --light-penalty-speed-coeff 250 \
--base-log-dir '/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation/updated_monotonic/wp_obs_info_speed_steer_ldist_goal_light' \
--carla-gpu 1 --code-gpu 1 \
--n-steps 20000 \
--lr 2e-4 \
--no-epochs 10 \
--no-minibatches 20 \
--clip 0.2 \
--videos \
--run-id 3 &


wait
