python ../run_code.py --algo PPO --task "self-driving" --scenarios "long_straight" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run1 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_long-straight/" --timesteps 8000000 --network 2_layer --lr 2e-4 --carla-gpu 2 --code-gpu 2 --steer-penalty-coeff 0 --const-collision-penalty 250 --collision-penalty-speed-coeff 250 --const-light-penalty 250 --light-penalty-speed-coeff 250 --clip 0.1 --ent-coef 0.005 --n-steps 10000 --no-epochs 10 &
sleep 60
python ../run_code.py --algo PPO --task "self-driving" --scenarios "long_straight" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run2 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_long-straight/" --timesteps 8000000 --network 2_layer --lr 2e-4 --carla-gpu 2 --code-gpu 2 --steer-penalty-coeff 0 --const-collision-penalty 250 --collision-penalty-speed-coeff 250 --const-light-penalty 250 --light-penalty-speed-coeff 250 --clip 0.1 --ent-coef 0.005 --n-steps 10000 --no-epochs 10 &
sleep 60
python ../run_code.py --algo PPO --task "self-driving" --scenarios "long_straight" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run3 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_long-straight/" --timesteps 8000000 --network 2_layer --lr 2e-4 --carla-gpu 1 --code-gpu 1 --steer-penalty-coeff 0 --const-collision-penalty 250 --collision-penalty-speed-coeff 250 --const-light-penalty 250 --light-penalty-speed-coeff 250 --clip 0.1 --ent-coef 0.005 --n-steps 10000 --no-epochs 10 &
sleep 60
python ../run_code.py --algo PPO --task "self-driving" --scenarios "long_straight" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run4 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_long-straight/" --timesteps 8000000 --network 2_layer --lr 2e-4 --carla-gpu 1 --code-gpu 1 --steer-penalty-coeff 0 --const-collision-penalty 250 --collision-penalty-speed-coeff 250 --const-light-penalty 250 --light-penalty-speed-coeff 250 --clip 0.1 --ent-coef 0.005 --n-steps 10000 --no-epochs 10 &
sleep 60
python ../run_code.py --algo PPO --task "self-driving" --scenarios "long_straight" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run5 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_long-straight/" --timesteps 8000000 --network 2_layer --lr 2e-4 --carla-gpu 1 --code-gpu 1 --steer-penalty-coeff 0 --const-collision-penalty 250 --collision-penalty-speed-coeff 250 --const-light-penalty 250 --light-penalty-speed-coeff 250 --clip 0.1 --ent-coef 0.005 --n-steps 10000 --no-epochs 10 &
sleep 60
