# # gpu 8
python ../run_code.py --algo SAC --task "self-driving" --scenarios "dynamic_navigation" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run1 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_dynamic-navigation_corrNstep/" --timesteps 8000000 --network 2_layer --lr 4e-4 --carla-gpu 0 --code-gpu 0 --steer-penalty-coeff 0 --const-collision-penalty 10 --collision-penalty-speed-coeff 10 --const-light-penalty 10 --light-penalty-speed-coeff 10 --buffer-size 1000000 --batch-size 512 --train-freq 512 --gradient-steps-per-iteration 100 --target-update-interval 1 --ent-coef 0.005 --n-steps 25 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --scenarios "dynamic_navigation" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run2 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_dynamic-navigation_corrNstep/" --timesteps 8000000 --network 2_layer --lr 4e-4 --carla-gpu 0 --code-gpu 0 --steer-penalty-coeff 0 --const-collision-penalty 10 --collision-penalty-speed-coeff 10 --const-light-penalty 10 --light-penalty-speed-coeff 10 --buffer-size 1000000 --batch-size 512 --train-freq 512 --gradient-steps-per-iteration 100 --target-update-interval 1 --ent-coef 0.005 --n-steps 25 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --scenarios "dynamic_navigation" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run3 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_dynamic-navigation_corrNstep/" --timesteps 8000000 --network 2_layer --lr 4e-4 --carla-gpu 3 --code-gpu 3 --steer-penalty-coeff 0 --const-collision-penalty 10 --collision-penalty-speed-coeff 10 --const-light-penalty 10 --light-penalty-speed-coeff 10 --buffer-size 1000000 --batch-size 512 --train-freq 512 --gradient-steps-per-iteration 100 --target-update-interval 1 --ent-coef 0.005 --n-steps 25 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --scenarios "dynamic_navigation" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run4 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_dynamic-navigation_corrNstep/" --timesteps 8000000 --network 2_layer --lr 4e-4 --carla-gpu 3 --code-gpu 3 --steer-penalty-coeff 0 --const-collision-penalty 10 --collision-penalty-speed-coeff 10 --const-light-penalty 10 --light-penalty-speed-coeff 10 --buffer-size 1000000 --batch-size 512 --train-freq 512 --gradient-steps-per-iteration 100 --target-update-interval 1 --ent-coef 0.005 --n-steps 25 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --scenarios "dynamic_navigation" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run5 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_dynamic-navigation_corrNstep/" --timesteps 8000000 --network 2_layer --lr 4e-4 --carla-gpu 3 --code-gpu 3 --steer-penalty-coeff 0 --const-collision-penalty 10 --collision-penalty-speed-coeff 10 --const-light-penalty 10 --light-penalty-speed-coeff 10 --buffer-size 1000000 --batch-size 512 --train-freq 512 --gradient-steps-per-iteration 100 --target-update-interval 1 --ent-coef 0.005 --n-steps 25 &
sleep 60
#python ../run_code.py --algo SAC --task "self-driving" --scenarios "dynamic_navigation" --num-npc 70 --input-type "wp_obs_info_speed_steer_ldist_goal_light" --run-id run1 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo_dynamic-navigation_corrNstep/" --timesteps 8000000 --network 2_layer --lr 4e-4 --carla-gpu 1 --code-gpu 1 --steer-penalty-coeff 0 --const-collision-penalty 250 --collision-penalty-speed-coeff 250 --const-light-penalty 250 --light-penalty-speed-coeff 250 --buffer-size 1000000 --batch-size 1024 --train-freq 4096 --gradient-steps-per-iteration 4 --target-update-interval 1 --ent-coef 0.005 --n-steps 25 &
#sleep 60
