# # gpu 8
python ../run_code.py --algo SAC --task "self-driving" --run-id run7 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 3000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 3 --carla-gpu 3 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef -1 --n-steps 25 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --run-id run8 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 3000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 3 --carla-gpu 3 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef -1 --n-steps 25 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --run-id run9 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 3000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 3 --carla-gpu 3 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef -1 --n-steps 25 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --run-id run10 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 3000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 1 --carla-gpu 1 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef -1 --n-steps 25 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --run-id run11 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 3000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 1 --carla-gpu 1 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef -1 --n-steps 25 &
sleep 60
python ../run_code.py --algo SAC --task "self-driving" --run-id run12 --base-log-dir "/zfsauton2/home/vkadi/projects/alta/alta-logs/sac_vs_ppo/" --timesteps 3000000 --lr 4e-4 --buffer-size 1000000 --network 2_layer --steer-penalty-coeff 0 --code-gpu 1 --carla-gpu 1 --const-collision-penalty 0 --collision-penalty-speed-coeff 0 --input-type wp --batch-size 512 --gradient-steps-per-iteration 1 --target-update-interval 1 --ent-coef -1 --n-steps 25 &
sleep 60
