#! /bin/bash
#SBATCH -N 1
#SBATCH -p long
#SBATCH --gres gpu:2
#SBATCH --ntasks-per-node 32
#SBATCH -t 3-12:00:00

source ~/.bashrc

trap "kill $(jobs -p)" EXIT

#echo commands to stdout
set -x

#move to working directory
# this job assumes:
# - all input data is stored in this directory 
# - all output should be stored in this directory 
cd /home/hiteshar/research/repos/alta/agents/tf



python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64/steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--use-pid-fs --special-sample --target-freq 10000 --opt-epochs 1 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 1 --code-gpu 1 \
--run-id 1 --videos >> dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64.txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64/lstjunc_steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--use-pid-fs --special-sample --target-freq 10000 --opt-epochs 1 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 1 --code-gpu 1 \
--run-id 2 --videos >> dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64.txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64/lstjunc_steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--use-pid-fs --special-sample --target-freq 10000 --opt-epochs 1 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 1 --code-gpu 1 \
--run-id 3 --videos >> dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64.txt 2>&1 &


sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_uniform_nn256_128_64/steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--use-pid-fs --target-freq 10000 --opt-epochs 1 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 1 --code-gpu 1 \
--run-id 1 --videos >> dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_uniform_nn256_128_64.txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_uniform_nn256_128_64/lstjunc_steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--use-pid-fs --target-freq 10000 --opt-epochs 1 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 1 --code-gpu 1 \
--run-id 2 --videos >> dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_uniform_nn256_128_64.txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_uniform_nn256_128_64/lstjunc_steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--use-pid-fs --target-freq 10000 --opt-epochs 1 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 1 --code-gpu 1 \
--run-id 3 --videos >> dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_uniform_nn256_128_64.txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_per_nn256_128_64_v2/steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--use-pid-fs --dqn-prioritized-replay --target-freq 10000 --opt-epochs 1 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 0 --code-gpu 0 \
--run-id 1 --videos >> dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_per_nn256_128_64_v2.txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_per_nn256_128_64_v2/steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--use-pid-fs --dqn-prioritized-replay --target-freq 10000 --opt-epochs 1 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 0 --code-gpu 0 \
--run-id 2 --videos >> dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_per_nn256_128_64_v2.txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_per_nn256_128_64_v2/steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--use-pid-fs --dqn-prioritized-replay --target-freq 10000 --opt-epochs 1 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 0 --code-gpu 0 \
--run-id 3 --videos >> dqn_dynamic_nav_steer7_speed_0_20_ac12_fs3_per_nn256_128_64_v2.txt 2>&1 &

wait
