#! /bin/bash
#SBATCH -N 1
#SBATCH -p long
#SBATCH --gres gpu:1
#SBATCH --ntasks-per-node 32
#SBATCH -t 7-12:00:00

source ~/.bashrc

trap "kill $(jobs -p)" EXIT

#echo commands to stdout
set -x

#move to working directory
# this job assumes:
# - all input data is stored in this directory 
# - all output should be stored in this directory 
cd /home/hiteshar/research/repos/alta/agents/tf

python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_expert_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64/steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--expert-buffer-path '/home/hiteshar/alta-logs/expert_data_gen_dyamic_nav/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs2_ss_nn256_128_64/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1_runid_1/dqn_measurements_weights_expert_buffer_100000.zip' \
--reduce-filename --expert-data-sample-percent 50 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--special-sample --use-pid-fs --target-freq 5000 --opt-epochs 2 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 0 --code-gpu 0 \
--run-id 1 --videos >>  .txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_expert_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64/steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--expert-buffer-path '/home/hiteshar/alta-logs/expert_data_gen_dyamic_nav/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs2_ss_nn256_128_64/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1_runid_1/dqn_measurements_weights_expert_buffer_100000.zip' \
--reduce-filename --expert-data-sample-percent 50 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--special-sample --use-pid-fs --target-freq 5000 --opt-epochs 2 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 0 --code-gpu 0 \
--run-id 2 --videos >> expert_dynamic_nav_nn256_128_64_fs2_ss_wp_orienation_target2k.txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_expert_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64/steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--expert-buffer-path '/home/hiteshar/alta-logs/expert_data_gen_dyamic_nav/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs2_ss_nn256_128_64/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1_runid_1/dqn_measurements_weights_expert_buffer_100000.zip' \
--reduce-filename --expert-data-sample-percent 50 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--special-sample --use-pid-fs --target-freq 5000 --opt-epochs 2 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 0 --code-gpu 0 \
--run-id 3 --videos >> expert_dynamic_nav_nn256_128_64_fs2_ss_wp_orienation_target2k.txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_expert_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64/steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--expert-buffer-path '/home/hiteshar/alta-logs/expert_data_gen_dyamic_nav/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs2_ss_nn256_128_64/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1_runid_1/dqn_measurements_weights_expert_buffer_100000.zip' \
--reduce-filename --expert-data-sample-percent 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--special-sample --use-pid-fs --target-freq 5000 --opt-epochs 2 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 0 --code-gpu 0 \
--run-id 1 --videos >> expert_dynamic_nav_nn256_128_64_fs2_ss_wp_orienation_target2k.txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_expert_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64/steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--expert-buffer-path '/home/hiteshar/alta-logs/expert_data_gen_dyamic_nav/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs2_ss_nn256_128_64/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1_runid_1/dqn_measurements_weights_expert_buffer_100000.zip' \
--reduce-filename --expert-data-sample-percent 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--special-sample --use-pid-fs --target-freq 5000 --opt-epochs 2 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 0 --code-gpu 0 \
--run-id 2 --videos >> expert_dynamic_nav_nn256_128_64_fs2_ss_wp_orienation_target2k.txt 2>&1 &

sleep 120
python run_code.py \
--algo DQN \
--input-type wp_obs_info_speed_steer_ldist_light \
--base-log-dir '/home/hiteshar/alta-logs/dqn_expert_dynamic_nav_steer7_speed_0_20_ac12_fs3_ss_nn256_128_64/steer7_throttle_0_20_ac12/' \
--scenarios dynamic_navigation --val-trials 25 \
--expert-buffer-path '/home/hiteshar/alta-logs/expert_data_gen_dyamic_nav/dqn_dynamic_nav_steer7_speed_0_20_ac12_fs2_ss_nn256_128_64/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1/algo_DQN_input_wp_angles_vecs_obs_info_speed_steer_ldist_light_nw_1_layer_lr_1e-05_dynamic_navigation_npc_100_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_2_pid_fs_dqn_n_3_r_norm_16_suc_r_75_const_r_1_runid_1/dqn_measurements_weights_expert_buffer_100000.zip' \
--reduce-filename --expert-data-sample-percent 25 \
--timesteps 10000000 \
--num-npc 50 \
--enable-brake \
--disable-semantic  \
--special-sample --use-pid-fs --target-freq 5000 --opt-epochs 2 --exp-final-eps 0.1 \
--const-collision-penalty 3  --steer-penalty-coeff  2 \
--const-light-penalty 3 --light-penalty-speed-coeff 3 \
--collision-penalty-speed-coeff 3 \
--fs 2 --reward-norm 16 --success-reward 75 --constant-reward 1 --dqn-n-step 3 \
--lr 1e-5 --buffer-size 1000000 \
--carla-gpu 0 --code-gpu 0 \
--run-id 3 --videos >> expert_dynamic_nav_nn256_128_64_fs2_ss_wp_orienation_target2k.txt 2>&1 &


wait