# Navigation Old VAE Before NeurIPS
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_navigation_reproduce algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_navigation_finetune_vae --inds 1 2 3 4 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_navigation_reproduce_w_brake algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_navigation_brake_finetune_vae --inds 1 2 3 4 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_navigation_reproduce_w_collision algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_navigation_brake_col_250.0_col_sp_250.0_finetune_vae --inds 1 2 3 4 &

# Navigation New VAE Post NeurIPS
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_navigation_reproduce_new_vae algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_navigation_finetune_vae --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_navigation_reproduce_w_brake_new_vae algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_navigation_brake_finetune_vae --inds 1 2 3 4 5 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_navigation_reproduce_w_only_collision_new_vae algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_navigation_col_250.0_col_sp_250.0_finetune_vae --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_navigation_reproduce_w_collision_fs_new_vae algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_navigation_brake_col_100.0_col_sp_100.0_fs_3_finetune_vae --inds 1 2 3 4 5 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_navigation_reproduce_w_collision_fs_new_vae algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_navigation_brake_col_100.0_col_sp_100.0_fs_5_finetune_vae --inds 1 2 3 4 5 &

# Dynamic Navigation New VAE Post NeurIPS
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_w_collision_new_vae algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_dynamic_navigation_npc_20_brake_col_50.0_col_sp_50.0_finetune_vae --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_w_collision_new_vae algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_dynamic_navigation_npc_20_brake_col_100.0_col_sp_100.0_finetune_vae --inds 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_w_collision_new_vae algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_dynamic_navigation_npc_20_brake_col_250.0_col_sp_250.0_finetune_vae --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_w_collision_new_vae algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_dynamic_navigation_npc_20_brake_col_500.0_col_sp_500.0_finetune_vae --inds 1 2 3 &

# Navigation SAC + AE
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_navigation_sac_ae_runs algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_ae_lr_0.0005_navigation_brake_col_100.0_col_sp_100.0_fs_3_fstack_3_train_vae --inds 1 2 3 &
# Dynamic Navigation SAC + AE
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_sac_ae_runs algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_ae_lr_0.0005_dynamic_navigation_npc_20_brake_col_100.0_col_sp_100.0_fs_3_fstack_3_train_vae --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_sac_ae_runs algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_ae_lr_0.0005_dynamic_navigation_npc_20_brake_col_250.0_col_sp_250.0_fs_3_fstack_3_train_vae --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_sac_ae_runs algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_ae_lr_0.0005_dynamic_navigation_npc_20_brake_col_500.0_col_sp_500.0_fs_3_fstack_3_train_vae --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_sac_ae_runs algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_ae_lr_0.0005_dynamic_navigation_pretrained_agent__npc_20_brake_col_100.0_col_sp_100.0_fs_3_fstack_3_finetune_vae --inds 4 5 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_sac_ae_runs algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_ae_lr_0.0005_dynamic_navigation_pretrained_agent__npc_20_brake_col_250.0_col_sp_250.0_fs_3_fstack_3_finetune_vae --inds 4 5 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_sac_ae_runs algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_ae_lr_0.0005_dynamic_navigation_pretrained_agent__npc_20_brake_col_500.0_col_sp_500.0_fs_3_fstack_3_finetune_vae --inds 4 5 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_sac_ae_runs algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_ae_lr_0.001_dynamic_navigation_npc_20_brake_col_100.0_col_sp_100.0_fstack_3_train_vae --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_sac_ae_runs algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_ae_lr_0.001_dynamic_navigation_npc_20_brake_col_250.0_col_sp_250.0_fstack_3_train_vae --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/benchmark_dynamic_navigation_sac_ae_runs algo_PPO_input_wp_vae_network_CustomPolicy2_lr_0.0002_ae_lr_0.001_dynamic_navigation_npc_20_brake_col_500.0_col_sp_500.0_fstack_3_train_vae --inds 1 2 3 &













# Pretrained AE (16_32_64_16)
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation_images/pretrained_ae algo_PPO_input_wp_vae_obs_info_speed_steer_ldist_goal_light_network_CustomPolicy2_lr_0.0002_ae_lr_0.0005_dynamic_navigation_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_fstack_3_n_10000_finetune_vae_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation_images/pretrained_ae algo_PPO_input_wp_vae_obs_info_speed_steer_ldist_goal_light_network_CustomPolicy2_lr_0.0002_ae_lr_0.0005_dynamic_navigation_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_n_10000_finetune_vae_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation_images/pretrained_ae algo_PPO_input_wp_vae_obs_info_speed_steer_ldist_goal_light_network_CustomPolicy2_lr_0.0002_ae_lr_0.001_dynamic_navigation_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_fstack_3_n_10000_finetune_vae_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation_images/pretrained_ae algo_PPO_input_wp_vae_obs_info_speed_steer_ldist_goal_light_network_CustomPolicy2_lr_0.0002_ae_lr_0.001_dynamic_navigation_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_n_10000_finetune_vae_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &

# Pretrained AE (16_32_64_64)
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation_images/pretrained_ae/16_32_64_64 algo_PPO_input_wp_vae_obs_info_speed_steer_ldist_goal_light_network_CustomPolicy2_lr_0.0002_ae_lr_0.0005_dynamic_navigation_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_fstack_3_n_10000_finetune_vae_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation_images/pretrained_ae/16_32_64_64 algo_PPO_input_wp_vae_obs_info_speed_steer_ldist_goal_light_network_CustomPolicy2_lr_0.0002_ae_lr_0.0005_dynamic_navigation_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_n_10000_finetune_vae_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation_images/pretrained_ae/16_32_64_64 algo_PPO_input_wp_vae_obs_info_speed_steer_ldist_goal_light_network_CustomPolicy2_lr_0.0002_ae_lr_0.001_dynamic_navigation_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_fstack_3_n_10000_finetune_vae_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation_images/pretrained_ae/16_32_64_64 algo_PPO_input_wp_vae_obs_info_speed_steer_ldist_goal_light_network_CustomPolicy2_lr_0.0002_ae_lr_0.001_dynamic_navigation_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_n_10000_finetune_vae_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &

# Pretrained AE (16_32_64_64) -> without obstacle info
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/dynamic_navigation_images/pretrained_ae/16_32_64_64 algo_PPO_input_wp_vae_speed_steer_ldist_goal_light_network_CustomPolicy2_lr_0.0002_ae_lr_0.001_dynamic_navigation_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_fstack_3_n_10000_finetune_vae_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &


# CNN (Reduced Image 64x64, Nature_64)
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/long_straight_jtn_images/cnn/nature_64 algo_PPO_binary_image__1channel__input_wp_cnn_obs_info_speed_steer_ldist_goal_light_network_CNN_lr_0.0002_long_straight_junction_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_fstack_3_n_10000_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/long_straight_jtn_images/cnn/nature_64 algo_PPO_binary_image__1channel__input_wp_cnn_obs_info_speed_steer_ldist_goal_light_network_CNN_lr_0.0002_long_straight_junction_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_fstack_5_n_10000_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/long_straight_jtn_images/cnn/nature_64 algo_PPO_binary_image__1channel__input_wp_cnn_obs_info_speed_steer_ldist_goal_light_network_CNN_lr_0.0006_long_straight_junction_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_fstack_3_n_10000_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/long_straight_jtn_images/cnn/nature_64 algo_PPO_binary_image__1channel__input_wp_cnn_obs_info_speed_steer_ldist_goal_light_network_CNN_lr_0.0006_long_straight_junction_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_fstack_5_n_10000_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/long_straight_jtn_images/cnn/nature_64 algo_PPO_binary_image__1channel__input_wp_cnn_obs_info_speed_steer_ldist_goal_light_network_CNN_lr_6e-05_long_straight_junction_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_fstack_3_n_10000_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 &
python plot_rewards.py /zfsauton2/home/tanmaya/projects/alta-logs/new_env/ppo_runs/long_straight_jtn_images/cnn/nature_64 algo_PPO_binary_image__1channel__input_wp_cnn_obs_info_speed_steer_ldist_goal_light_network_CNN_lr_6e-05_long_straight_junction_npc_70_col_250.0_col_sp_250.0_light_250.0_light_sp_250.0_fstack_5_n_10000_epochs_10__clip_0.2__mb_10_ --inds 1 2 3 & 