cd '/zfsauton2/home/hiteshar/anaconda3/envs/st_carla9.4_py35/lib/python3.5/site-packages/stable_baselines/common/'
import base_class
cd /zfsauton2/home/hiteshar/research/alta/agents/tf/ 
import custom_replay_buffer

import os, cloudpickle
import pandas as pd 
/home/scratch/hiteshar/research/alta-logs/dqn_replayRL1/longst_steer_throttle_3/algo_DQN_input_wp_obs_info_speed_steer_ldist_goal_light_network_1_layer_lr_1e-05_long_straight_npc_50_buffer_1000000_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_fs_5_use_pid_fs_/algo_DQN_input_wp_obs_info_speed_steer_ldist_goal_light_network_1_layer_lr_1e-05_long_straight_npc_50_buffer_1000000_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_fs_5_use_pid_fs__runid_2/buffer_training/test_results_learn_with_buffer.csv
/home/scratch/hiteshar/research/alta-logs/dqn_replayRL1/longst_steer_throttle_1/algo_DQN_input_wp_obs_info_speed_steer_ldist_goal_light_network_1_layer_lr_1e-05_long_straight_npc_50_buffer_1000000_brake_enable_static_1000__col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_fs_5_use_pid_fs_/algo_DQN_input_wp_obs_info_speed_steer_ldist_goal_light_network_1_layer_lr_1e-05_long_straight_npc_50_buffer_1000000_brake_enable_static_1000__col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_fs_5_use_pid_fs__runid_2/buffer_training/
/home/scratch/hiteshar/research/alta-logs/dqn_replayRL1/longst_steer_throttle_2/algo_DQN_input_wp_obs_info_speed_steer_ldist_goal_light_network_1_layer_lr_1e-05_long_straight_npc_50_buffer_1000000_brake_enable_static_1000__col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_fs_5_use_pid_fs_/algo_DQN_input_wp_obs_info_speed_steer_ldist_goal_light_network_1_layer_lr_1e-05_long_straight_npc_50_buffer_1000000_brake_enable_static_1000__col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_fs_5_use_pid_fs__runid_1/buffer_training/
/home/scratch/hiteshar/research/alta-logs/dqn_replayRL1_oldR/longst_steer_throttle_1/algo_DQN_input_wp_obs_info_speed_steer_ldist_goal_light_network_1_layer_lr_1e-05_long_straight_npc_50_buffer_1000000_brake_enable_static_1000__col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_use_pid_fs_/algo_DQN_input_wp_obs_info_speed_steer_ldist_goal_light_network_1_layer_lr_1e-05_long_straight_npc_50_buffer_1000000_brake_enable_static_1000__col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_use_pid_fs__runid_2/buffer_training/
/home/scratch/hiteshar/research/alta-logs/dqn_replayRL1/longst_steer_throttle_1/algo_DQN_input_wp_obs_info_speed_steer_ldist_goal_light_network_1_layer_lr_3e-06_long_straight_npc_50_buffer_1000000_brake_enable_static_1000__col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_fs_5_use_pid_fs_/algo_DQN_input_wp_obs_info_speed_steer_ldist_goal_light_network_1_layer_lr_3e-06_long_straight_npc_50_buffer_1000000_brake_enable_static_1000__col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_fs_5_use_pid_fs__runid_2/
cd /home/scratch/hiteshar/research/alta-logs/dqn_long_straight_replay3/algo_DQN_input_wp_obs_info_speed_steer_ldist_goal_light_network_1_layer_lr_3e-05_long_straight_npc_50_buffer_1000000_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_use_pid_fs_
cd /home/scratch/hiteshar/research/alta-logs/dqn_dynamic_nav_improv_large_steer_ac12_ss_fixed/junc_steer7_throttle_0_20_ac_12/algo_DQN_input_wp_obs_info_speed_steer_ldist_light_nw_1_layer_lr_3e-05_exp_0.1_dynamic_navigation_pre_tfs_npc_70_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_3_pid_fs_ss_dqn_n_3_r_norm_24_suc_r_100_const_r_1/algo_DQN_input_wp_obs_info_speed_steer_ldist_light_nw_1_layer_lr_3e-05_exp_0.1_dynamic_navigation_pre_tfs_npc_70_brake_col_3.0_col_sp_3.0_light_3.0_light_sp_3.0_steer_pen_2.0_fs_3_pid_fs_ss_dqn_n_3_r_norm_24_suc_r_100_const_r_1_runid_2
load_path='dqn_measurements_weights400000.zip'
data, params = base_class.BaseRLModel._load_from_file(load_path)
buffer = data['replay_buffer']
df  = pd.DataFrame(buffer._storage)
done_df = df[df[4] ==1]

done_df.groupby(1).describe()[2]
done_df_car = done_df[ done_df[5] == 1]
done_df_car.groupby(1).describe()[2]