#! /bin/bash
#SBATCH -N 1
#SBATCH -p GPU-AI
#SBATCH --ntasks-per-node 8
#SBATCH --gres=gpu:volta32:5
#SBATCH -t 48:00:00

trap "kill $(jobs -p)" EXIT

#echo commands to stdout
set -x

#move to working directory
# this job assumes:
# - all input data is stored in this directory 
# - all output should be stored in this directory 
cd /pylon5/cc5fpsp/tanmaya/alta

gpu=0
port=3100
env="Carla-9-4"
for lr in 1e-5 3e-5 5e-5 7e-5 9e-5
do
    CUDA_VISIBLE_DEVICES=$gpu python train/torch/train.py \
    --algo DDPG \
    --actor-lr $lr \
    --critic-lr $lr \
    --dropout-rate 0.0 \
    --pretrained none \
    --carla-port $port \
    --env-name $env \
    --start-steps 0 \
    --max-steps 300000 \
    --replay-size 100000 \
    --fixed-replay \
    --batch-size 256 \
    --log-interval 100 \
    --log-dir logs/$env/04_19 \
    --save-dir weights/$env/04_19 \
    --discount 0.99 \
    --file-name DDPG-ALR$lr-CLR$lr-wo-dropout-fixed-replay-100k > port$port.txt 2>&1 &
    gpu=$(((gpu+1) % 9))
    port=$((port + 10))
done

wait
